### PR TITLE
add build-preview script and netlify configuration

### PR DESCRIPTION
**Pull request by wotnak**

### CODE REVIEW

**Comment by paul121** [comment]
This is awesome! It's kinda a bummer that we need to configure this repo as a netlify site itself... but it makes sense. Was there anything you needed to do on the Netlify side of things for this? Just create a new "site" and connect to this repo?

The more I'm reading about deploy hooks the more I realize that they are still very coupled to a branch from the netlify source project. In other words, you can't use a build hook to create an entire new build with a unique URL - it will only trigger a rebuild for an existing branch. https://docs.netlify.com/configure-builds/build-hooks/

**Comment by wotnak** [comment]
Yeah, netlify sites are very coupled to the repo and its branches. Configuring this repo as a netlify site was the easiest way to get deploy previews on pull requests.

> Was there anything you needed to do on the Netlify side of things for this? Just create a new "site" and connect to this repo?

No, just creating a new site connected to this repo was enough. Build command and public path are configured in `netlify.toml` so there's no need to configure them through netlify dashboard. The only thing on the netlify side I've done was setting a custom project name/domain, so it's clear that the site is blog preview and not an actual production site.

**Comment by paul121** [comment]
> The only thing on the netlify side I've done was setting a custom project name/domain, so it's clear that the site is blog preview and not an actual production site.

Right! And it's possible to leave this unconfigured as well, yes? Is that simply not configuring a domain? Would be good to make sure it isn't getting indexed by search engines. I imagine netlify might have a setting for this if not disabled by default

**Comment by wotnak** [comment]
Yes, domain can be left unconfigured. Deploy previews already have `X-Robots-Tag: noindex` header set, so they won't be indexed. Pushing to the main branch will cause regular netlify deploy, so we will need to configure netlify to always set the noindex header.

**Pull request closed without merging**
